import { SolarPanel } from "lucide-react";

export const AI_ASSISTANTS = [
  {
    id: "AMAZONAS_ENERGIA",
    name: "Amazonas Energia",
    description: "",
    icon: SolarPanel,
    color: "from-amber-500 via-orange-500 to-red-500",
    borderColor: "border-amber-300",
    bgColor: "bg-amber-50",
    status: "active",
  },
  {
    id: "CELESC",
    name: "Celesc (SC)",
    description: "",
    icon: SolarPanel,
    color: "from-blue-500 via-sky-500 to-cyan-500",
    borderColor: "border-blue-300",
    bgColor: "bg-blue-50",
    status: "active",
  },
  {
    id: "CEMIG",
    name: "Cemig (MG)",
    description: "",
    icon: SolarPanel,
    color: "from-yellow-500 via-amber-500 to-orange-500",
    borderColor: "border-yellow-300",
    bgColor: "bg-yellow-50",
    status: "active",
  },
  {
    id: "COPEL",
    name: "Copel (PR)",
    description: "",
    icon: SolarPanel,
    color: "from-emerald-500 via-green-500 to-teal-500",
    borderColor: "border-emerald-300",
    bgColor: "bg-emerald-50",
    status: "active",
  },
  {
    id: "CPFL",
    name: "CPFL Energia",
    description: "",
    icon: SolarPanel,
    color: "from-indigo-500 via-purple-500 to-pink-500",
    borderColor: "border-indigo-300",
    bgColor: "bg-indigo-50",
    status: "active",
  },
  {
    id: "EDP_ES",
    name: "EDP Espírito Santo",
    description: "",
    icon: SolarPanel,
    color: "from-red-500 via-rose-500 to-pink-500",
    borderColor: "border-red-300",
    bgColor: "bg-red-50",
    status: "active",
  },
  {
    id: "EDP_SP",
    name: "EDP São Paulo",
    description: "",
    icon: SolarPanel,
    color: "from-purple-500 via-fuchsia-500 to-pink-500",
    borderColor: "border-purple-300",
    bgColor: "bg-purple-50",
    status: "active",
  },
  {
    id: "ENEL",
    name: "Enel Brasil",
    description: "",
    icon: SolarPanel,
    color: "from-red-500 via-orange-500 to-yellow-500",
    borderColor: "border-red-300",
    bgColor: "bg-red-50",
    status: "active",
  },
  {
    id: "EQUATORIAL",
    name: "Equatorial Energia",
    description: "",
    icon: SolarPanel,
    color: "from-lime-500 via-green-500 to-emerald-500",
    borderColor: "border-lime-300",
    bgColor: "bg-lime-50",
    status: "active",
  },
  {
    id: "FECOERGS",
    name: "Fecoergs (RS)",
    description: "",
    icon: SolarPanel,
    color: "from-gray-500 via-slate-500 to-zinc-500",
    borderColor: "border-gray-300",
    bgColor: "bg-gray-50",
    status: "active",
  },
  {
    id: "LIGHT",
    name: "Light (RJ)",
    description: "",
    icon: SolarPanel,
    color: "from-yellow-400 via-orange-400 to-red-400",
    borderColor: "border-yellow-300",
    bgColor: "bg-yellow-50",
    status: "active",
  },
  {
    id: "NEOENERGIA",
    name: "Neoenergia",
    description: "",
    icon: SolarPanel,
    color: "from-sky-500 via-blue-500 to-indigo-500",
    borderColor: "border-sky-300",
    bgColor: "bg-sky-50",
    status: "active",
  },
  {
    id: "RORAIMA_ENERGIA",
    name: "Roraima Energia",
    description: "",
    icon: SolarPanel,
    color: "from-orange-500 via-amber-500 to-yellow-500",
    borderColor: "border-orange-300",
    bgColor: "bg-orange-50",
    status: "active",
  },
];
